### ISSUE TITLE
add further instructions to the README and Docker description

### ISSUE THREAD

**Issue by RMKD** [MycroftAI/docker-mycroft#13]
after launching via `docker run --device /dev/snd:/dev/snd --privileged -it mycroftai/mycroft /bin/bash`, I ran `supervisord`, but am not sure how to test/use the apparently running services:
```
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  18260  2300 ?        Ss   01:50   0:00 /bin/bash
root        13  0.0  0.6  60868 14236 ?        Ss   01:50   0:01 /usr/bin/python /usr/bin/supervisord
root        14  0.0  0.0  17972   236 ?        S    01:50   0:00 bash /mycroft/ai/start.sh service
root        15  0.0  0.0  17972   236 ?        S    01:50   0:00 bash /mycroft/ai/start.sh voice
root        16  0.0  0.0  17972   232 ?        S    01:50   0:00 bash /mycroft/ai/start.sh skills
root        26  0.1  1.3 1046844 26988 ?       Sl   01:50   0:06 python /mycroft/ai/mycroft/skills/main.py
root        27  0.1  1.5 1222096 31636 ?       Sl   01:50   0:06 python /mycroft/ai/mycroft/client/speech/main.py
root        28  0.5  1.0  76352 20588 ?        S    01:50   0:29 python /mycroft/ai/mycroft/messagebus/service/main.py
root        86  0.0  0.1  15568  2120 ?        R+   03:13   0:00 ps aux
```

if I open up port 8000 by adding `-p 8000:8000` to the docker run command, I get this error trying to open localhost:8000 in a browser:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```

It would be great if the README had a fourth bullet indicating how to verify that the services are running and what to try next.

**Comment by btotharye** [comment]
going to close this issue now since most of this has been documented now, if its still confusing please let me know.
