### ISSUE TITLE
error messages during docker build 

### ISSUE THREAD

**Issue by DewiBrynJones** [MycroftAI/docker-mycroft#37]
I'm new to MyCroft, but, after fixing #36,  and following the steps at:

https://github.com/MycroftAI/docker-mycroft#how-to-build-and-run

I get: 

```
Searching for for 'skill-volume'...'skill-volume' skill was not found
Searching for for 'skill-weather'...'skill-weather' skill was not found
Searching for for 'skill-wiki'...'skill-wiki' skill was not found
Searching for for 'fallback-aiml'...installing
Installing from: https://github.com/forslund/fallback-aiml.git
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.1-py2.7.egg/mycroft/messagebus/send.py", line 53, in <module>
    ws = create_connection(url)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 104, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 266, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options))
  File "/usr/local/lib/python2.7/site-packages/websocket/_http.py", line 63, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python2.7/site-packages/websocket/_http.py", line 116, in _open_socket
    raise err
socket.error: [Errno 111] Connection refused
/usr/local/bin/msm: line 105: 10:23:00.086: command not found
Cloning into 'fallback-aiml'...
  Installing requirements...
/usr/local/bin/msm: line 325: workon: command not found
ERROR: Unable to activate 'mycroft' virtualenv, requirements not installed.
Searching for for 'skill-mark1-demo'...'skill-mark1-demo' skill was not found
msm: error 202
Starting service…
Service started
Starting service…
Service started
Removing intermediate container 29ef942e0dd6
 ---> bd7701319b0c
Step 12/12 : ENTRYPOINT ["tail", "-f", "/var/log/mycroft-skills.log"]
 ---> Running in fe5e4335cfce
Removing intermediate container fe5e4335cfce
 ---> 188b76af106d
Successfully built 188b76af106d
```

which results in 

![delwedd](https://user-images.githubusercontent.com/8668769/35622418-b9ece1f8-067f-11e8-9574-c29daffe87be.png)

when running cli.sh inside the container.

**Comment by ConorIA** [comment]
FWIW, I'm seeing those same error messages on the image that I've pulled from Docker Hub.

**Comment by DewiBrynJones** [comment]
Great! I can confirm that the docker build does not produce this error any more. 

Diolch!

**Comment by payalord** [comment]
Got this error today:
```
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/messagebus/client/client.py", line 84, in on_error
    self.emitter.emit('error', error)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/messagebus/client/client.py", line 84, in on_error
    self.emitter.emit('error', error)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
2020-06-22 21:32:19.905 | ERROR    |    27 | mycroft.messagebus.client.client:on_error:88 | Exception closing websocket: ConnectionRefusedError(111, 'Connection refused')
2020-06-22 21:32:19.909 | WARNING  |    27 | mycroft.messagebus.client.client:on_error:91 | Message Bus Client will reconnect in 60 seconds.
```
