### ISSUE TITLE
docker-mycroft connection refused

### ISSUE THREAD

**Issue by payalord** [MycroftAI/docker-mycroft#70]
Got this error today:
```
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/messagebus/client/client.py", line 84, in on_error
    self.emitter.emit('error', error)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/messagebus/client/client.py", line 84, in on_error
    self.emitter.emit('error', error)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 120, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 190, in _open_socket
    raise err
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/websocket/_http.py", line 170, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
2020-06-22 21:32:19.905 | ERROR    |    27 | mycroft.messagebus.client.client:on_error:88 | Exception closing websocket: ConnectionRefusedError(111, 'Connection refused')
2020-06-22 21:32:19.909 | WARNING  |    27 | mycroft.messagebus.client.client:on_error:91 | Message Bus Client will reconnect in 60 seconds.
```
Probably related issues #37

**Comment by payalord** [comment]
This happens after mycroft docker container restarts. Everytime.

**Comment by jorritsmit** [comment]
removing the container seems to work for me
