### ISSUE TITLE
docker build fails with "ERROR: Command errored out with exit status 1"

### ISSUE THREAD

**Issue by msebald** [MycroftAI/docker-mycroft#71]
Hi,

I was trying to build the latest commit 38be3e2 using "docker build -t mycroft .". Unfortunately this did not work:

```
Collecting msm==0.8.8
  Using cached msm-0.8.8-py3-none-any.whl (25 kB)
Collecting msk==0.3.16
  Downloading msk-0.3.16-py3-none-any.whl (47 kB)
Collecting adapt-parser==0.3.7
  Downloading adapt-parser-0.3.7.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/mycroft/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9u69j8kb/adapt-parser/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9u69j8kb/adapt-parser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9u69j8kb/adapt-parser/pip-egg-info
         cwd: /tmp/pip-install-9u69j8kb/adapt-parser/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9u69j8kb/adapt-parser/setup.py", line 21, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1825: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.2.4 is available.
You should consider upgrading via the '/opt/mycroft/.venv/bin/python -m pip install --upgrade pip' command.
Warning: Failed to install required dependencies. Continue? y/N
The command '/bin/sh -c set -x  && sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list    && apt-get update       && apt-get -y install git python3 python3-pip locales sudo      && pip3 install future msm      && git clone https://github.com/MycroftAI/mycroft-core.git /opt/mycroft      && cd /opt/mycroft      && mkdir /opt/mycroft/skills    && CI=true /opt/mycroft/./dev_setup.sh --allow-root -sm         && mkdir /opt/mycroft/scripts/logs      && touch /opt/mycroft/scripts/logs/mycroft-bus.log   && touch /opt/mycroft/scripts/logs/mycroft-voice.log    && touch /opt/mycroft/scripts/logs/mycroft-skills.log   && touch /opt/mycroft/scripts/logs/mycroft-audio.log    && apt-get -y autoremove        && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1
```

I deleted everything and tried again. Same result.

Is this a bug or a problem with my setup?

**Comment by forslund** [comment]
It's a bug. I posted a fix (hopefully)  over here: https://github.com/MycroftAI/mycroft-core/pull/2746

**Comment by krisgesling** [comment]
Hey @msebald the fix has been merged into the dev branch. Thanks for raising it!

**Comment by msebald** [comment]
@forslund @krisgesling It works, I was able to get and build the Docker image here. It is now up and running. Thank you for the fix and merge! :-)
