### ISSUE TITLE
Mycroft Docker - Error after updates

### ISSUE THREAD

**Issue by GoldenbyteGH** [MycroftAI/docker-mycroft#73]
Python Exception after "git pull" comand on mycroft-core folder

`(.venv) root@686b055bb9b2:/opt/mycroft# ./start-mycroft.sh cli
Initializing...
Changing ownership of /opt/mycroft to user: with group: root
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting cli
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/mycroft/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/opt/mycroft/mycroft/api/__init__.py", line 22, in <module>
    from mycroft.configuration import Configuration
  File "/opt/mycroft/mycroft/configuration/__init__.py", line 15, in <module>
    from .config import Configuration, LocalConf, RemoteConf
  File "/opt/mycroft/mycroft/configuration/config.py", line 25, in <module>
    from mycroft.util.json_helper import load_commented_json, merge_dict
  File "/opt/mycroft/mycroft/util/__init__.py", line 24, in <module>
    from mycroft.util.format import nice_number
  File "/opt/mycroft/mycroft/util/format.py", line 34, in <module>
    from lingua_franca import get_default_loc
ImportError: cannot import name 'get_default_loc'
(.venv) root@686b055bb9b2:/opt/mycroft# 
`

**To Reproduce**
When a new skill is added, mycroft suggest to update using "git pull" command, but it causes the reported error

**Environment (please complete the following information):**
 - Device type: docker on ubuntu server]
 - OS: Ubuntu]
 - Mycroft-core version:  20.08

I've tried to pull a new version from DokerHub, but I am not able to download the 21.x

**Comment by TheLastProject** [comment]
This doesn't sound like a docker issue, could you please recreate your issue on https://github.com/MycroftAI/mycroft-core/issues?

**Comment by forslund** [comment]
I think this is that a new requirement has been installed in core, can you try to run the dev_setup.sh in the mycroft-core folder as well to update the requirements?
