### ISSUE TITLE
Docker image error: "pa_context_connect() failed: Connection refused" with audiotest

### ISSUE THREAD

**Issue by auwsom** [MycroftAI/docker-mycroft#74]
Fresh docker image following the install docker at link below, so I would expect it to work out of the box. Using `docker exec -it mycroft /bin/bash` to start. Then `mycroft-start audiotest` and I get the error in the title. I've seen this error, I think when setting up Mycroft in a VM and it was because I had installed as root. I'm a little confused here because the Docker container doesnt have a user beside root. 

The packages are installed into /opt so I might assume I'm supposed to create a user, so I did, and use the command below to start the container with that user, but I get another error: 

```
Changing ownership of /opt/mycroft to user: with group: abc
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
Starting audiotest
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
....
  File "/opt/mycroft/mycroft/configuration/config.py", line 17, in <module>
    import inflection
ModuleNotFoundError: No module named 'inflection'
```
I'm working through the errors for clues, but either way, the instructions for Docker below are lacking the necessary steps to make it work.

https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/docker

**Comment by auwsom** [comment]
Hang in there with me for a bit.. this is going to be a lengthy post with a lot of details about a journey to get the docker image working. 

- The missing packages was because of the virtual environment not being activated. I thought this might be the case after thinking about it, but it's worth keeping on this thread for others with the same error. Installing inflection only results in having another package not found. 
- The biggest challenge with the docker-mycroft image is that there is no user other than root set. Pulseaudio gives some hints tha its not intended to run as root, and in some tests I had the error in the title resolve by just typing `pulseaudio` as a user instead of root. 
- I have about a week's worth of progress to document, so I'll start at the conclusion and work back for others with similar errors, with random hints as I clean up open tabs.
- I got the container working using a standardized and commonly used image (lower chances of malware) 'minideb' image from DockerHub. The minideb images are curated by Docker itself I believe. There is an Ubuntu image of a similar size around 50mb that also has a good record and has been hardened for security by Canonical. I'll probably build a fresh version from that. 
- These minimal images dont have a lot of utilities. minideb didnt even have ps, even though it runs on SysV instead of SystemD. If you see "OSError: [Errno -9996] Invalid input device (no default output device)" you may need to `apt install pulseaudio`.
- After getting the initial 'Connection refused' error to resolve the first time, by installing a user (see commands below), it is essential to add that user to the 'audio' group. (adding user 'mycroft' would work, but 'ubuntu' is used in the mycroft code (will find) so using that)
- Installing alsa-utils (~7mb) will give tools like aplay and arecord. `aplay -l` should show the same soundcard for root as user 'ubuntu' after its been added to the audio group. It should try to play a test sound from alsa-utils with the command below.
- With a user and alsa happy, pulseaudio needs several args passed to it with the container creation.
- The key here was this post: https://github.com/TheBiggerGuy/docker-pulseaudio-example/issues/1
- For this docker test image: https://hub.docker.com/r/thebiggerguy/docker-pulseaudio-example/
- It is specifically to test audio in a basic docker image. The default scripts dont work, but the code in the issue does.
- The args in that issue are similar to the docker setup from Mycroft docs: https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/docker
- The last round of problems was getting errors like: "Unable to autolaunch a dbus-daemon without a $DISPLAY for X11" and "Unable to contact D-Bus: : /usr/bin/dbus-launch docker" and errors about "/root/.config/pulse/cookie"
- Checking this cookie reveal a directory, which is because "If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v will create the endpoint for you. It is always created as a directory." https://stackoverflow.com/a/47099098/4240654
- Deleting that dir and a making a new cookie file, and chmodding to 777 removed the cookie errors. 
- And finally, `run`ing the docker container from a non-root user on the host removed the X11 and Dbus errors!

- Of course, run the `mycroft-start audiotest` command to make sure the mic is also working. 
- If there are "no soundcards" with `aplay -l` as root, in a VM.. run `sudo modprobe snd-hda-intel` to see if the kernel has audio modules. A lot of the server image kernels dont, to keep them lightweight. 

```
useradd --create-home --shell /bin/bash --password ubuntu ubuntu 
usermod -aG audio ubuntu
apt install alsa-utils
su ubuntu && cd ~
aplay -l
aplay /usr/share/sounds/alsa/Noise.wav
pulseaudio 
(pulseaudio --help, if necessary)
```
`docker run -t --detach --volume /media/username/programs/mycroft:/root/.mycroft --env PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native  -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native  -v ~/.config/pulse/cookie:/root/.config/pulse/cookie  -p 8181:8181  --name mini-mycroft minideb-mycroft`

- Portainer.io is a great docker container manager for linux - web-based. 
- pip can be upgraded with `python -m pip install --upgrade pip` to remove that error. There is another error for 'behave' that is for the testing suite Mycroft is using. https://mycroft.ai/blog/the-voight-kampff-test/
- it would be great to have some of this info added to the Mycroft Docker installation docs

**Comment by auwsom** [comment]
I'm creating a working version of the Mycroft docker image from here: https://hub.docker.com/r/mycroftai/docker-mycroft/
I will upload this to DockerHub here:
Here are the exact commands necessary. They could be added to the Mycroft DockerHub repo dockerfile.
First create the container with this command as root or sudo:
`docker run --tty --detach --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native  --volume ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native  -v ~/.config/pulse/cookie:/root/.config/pulse/cookie -v ~/.config/pulse/cookie:/home/user/.config/pulse/cookie -p 8181:8181 --name mycroft-docker mycroftai/docker-mycroft`
```
useradd -d /home/user --shell /bin/bash --password user user

d
```


https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/docker
